<?php $this->layout('layout::default', ['title' => 'Stalk-A-User']) ?>

<h1 class="text-center">Stalk-A-User</h1>
<p class="text-center">Inform a twitter user and we will get his address for you</p>

<div id="gallery" class="row"></div>

<div class="text-center">
    <button id="more" class="btn btn-primary">More...</button><br /><br />
</div>

<div id="modal" class="modal fade">
    <div class="modal-dialog modal-lg">
        <div class="modal-content">
            <div class="modal-header">
              <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
              <h4 id="modal-title" class="modal-title"></h4>
            </div>
            <div class="modal-body">
                <img id="modal-image" src="" alt="" class="img-responsive" />
            </div>
            <div class="modal-footer">
                <p id="modal-caption"></p>
            </div>
        </div>
    </div>
</div>

