<?php $this->headTitle('Stalk-A-User'); ?>

<h1 class="text-center">Stalk-A-User</h1>
<p class="text-center">Inform a twitter user and we will get his address for you</p>



<div class="text-center">
    <div class="col-md-12">
       <form>
          <div class="form-group">
            <label for="twitter_user">Twitter User Name</label>
            <input type="input" class="form-control" id="twitter_user"  placeholder="Enter user">
            <small id="twitterUser" class="form-text text-muted">We'll stalk the hell out of him.</small>
          </div>
          <button type="submit" class="btn btn-primary">Submit</button>
        </form>
    </div>
</div>

