<?php $this->headTitle('Stalk-A-User'); ?>

<h1 class="text-center">Stalk-A-User</h1>
<p class="text-center">Inform a twitter user and we will get his address for you</p>



<div class="text-center">
    <div class="col-md-12">
      <form action="" method="post">
          <div class="form-group">
            <label for="twitter_user">Twitter User Name</label>
            <input type="input" name="twitter_user" class="form-control" id="twitter_user"  placeholder="Enter user">
            <small id="twitterUser" class="form-text text-muted">We'll stalk the hell out of him.</small>
          </div>
          <button type="submit" class="btn btn-primary">Submit</button>
        </form>
    </div>
</div>
<div>
    
    <div class="col-md-10">
      <?php if($data['result']) { ?>
      <ul>
      <li><?php echo $data['user_name']; ?></li>
      <li>Place name: <?php echo $data["localidade"]; ?></li>
      <li>Google Maps Link: <a href="<?php echo $data["link"]; ?>" target="_blank"><?php echo $data["localidade"]; ?></a></li>
      </ul>
     <?php } else { ?>
     <?php echo $data['user_name']; ?>
     <?php } ?>
    </div>
   
</div>

